jasper-software/jasper

configure
configure.ac

This is a patch from the Fedora package, introduced Oct 18 2005: Remove libGL dependancy

1.701.0-GL

---

src/libjasper/include/jasper/jas_config2.h

The file jas_malloc.c uses the keyword 'inline' that is not supported by older version of Visual Studio. This patch resolves that issue. If I understand it correctly the file jas_config2.h is used under Windows only. I can also add a check for '_MSC_VER' if you prefer that.

Fixed 'inline' for older version of Visual Studio.

---

CMakeLists.txt

When doing static-only builds (-DJAS_ENABLE_SHARED=OFF) the install
process fails due to an invalid RPATH:
...............................................................
CMake Error at src/appl/cmake_install.cmake:45 (file):
file RPATH_CHANGE could not write new RPATH:
/usr/lib
to the file:
/br/output/host/usr/xtensa-buildroot-linux-uclibc/sysroot/usr/bin/jasper
No valid ELF RPATH or RUNPATH entry exists in the file;
Call Stack (most recent call first):
cmake_install.cmake:42 (include)
...............................................................
RPATH shouldn't be changed when doing static-only builds.
Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>

CMakeLists.txt: only change RPATH when building for shared

---

build/jasper.pc.in

Hey @mdadams 
I've made the `.pc` file slightly more idiomatic and humanly readable. The current file for instance:
```
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib
includedir=/usr/include
```
compared to say glib-2.0 (https://github.com/GNOME/glib/blob/master/glib-2.0.pc.in):
```
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib64
includedir=${prefix}/include
```
Given that the `GNUInstallDirs` module does not have an `exec_prefix` analogue, I suggest recycling the normal prefix (which is what 99.9% of distros do anyways). The main advantage is that it makes it easier to read and potentially inserts only one massive path (`@CMAKE_INSTALL_PREFIX@`) into the .pc file, instead of inserting it 4 times.
Also, please make another release after (possibly) merging this PR.

Make .pc file more Autotools-idiomatic

---

build/jasper.pc.in

Using full paths is more versatile. The current solution
breaks when specifying an absolute path for `CMAKE_INSTALL_INCLUDEDIR`
which is an otherwise supported option by CMake's `GNUInstallDirs`.
CMake does not support Autoconf-style `${prefix}`-pseudo variables,
hence trying to emulate the behaviour gains us nothing and breaks
providing absolute paths to `CMAKE_INSTALL_LIBDIR`.

Use full CMake paths in pkg-config template

---

src/libjasper/CMakeLists.txt

On win32 the dll is to be installed in prefix/bin instead of prefix/lib

Fix library runtime destination

---

src/libjasper/include/jasper/jas_math.h

Mostly fixing bad copy-n-paste issues, or functions added without any
comment.

Correct or add comments for jas_safe_* functions

---

src/libjasper/jp2/jp2_enc.c

Fixes building with -Werror=implicit-function-declaration.

Include jasper/jas_debug.h when using jas_eprintf

---

src/libjasper/base/jas_image.c

Regarding CVE-2018-19539.
Fix by Markus Koschany <apo@debian.org>.
From https://gist.github.com/apoleon/7c0f3a0c28437c18fee8a51b1aa16164.

Check data in jas_image

---

src/libjasper/jpc/jpc_dec.c
src/libjasper/jpc/jpc_t2cod.c

- [Conformance testing results of jasper 2.0.19.xlsx](https://github.com/jasper-software/jasper/files/4992408/Conformance.testing.results.of.jasper.2.0.19.xlsx) shows that the current version of JasPer does not conform to the JPEG 2000 conformance testing defined as ISO/IEC 15444-4.
https://github.com/jasper-software/jasper/pull/221/commits/3204e675eabf9ac0145a48f26820aeda26924e5a
- **Why**: If the LSB of the Sqcd or Sqcc in the QCD or QCC marker is equal to "1" , this incorrect calculation of derived stepsizes produces wrongly reconstructed sample values.
- **How**: The calculation of derived stepsizes in `calcstepsizes()` has been fixed according to the JPEG 2000 spec defined as the ISO/IEC 15444-1.
https://github.com/jasper-software/jasper/pull/221/commits/1c220a140086d58d33b096bcfd5bae …

Fixes for conformance testing

---

src/libjasper/jpc/jpc_t2dec.c

**Why**: If EPH markers are required (by setting the third LSB of Scod parameter to "1" in the COD marker segment, see A.6.1), each packet header in any given tile-part shall be postpended with an EPH marker segment. jpc_dec_lookahead() never returns a value out of the range from 0xff80 to 0xffff, however, a broken bitstream may have a value in this range. Therefore, `if (jpc_dec_lookahead(pkthdrstream) == JPC_MS_EPH)` cannot check the case that the packet header has not been correctly postpended with an EPH marker (= 0xff92).
**How**: Delete https://github.com/jasper-software/jasper/blob/9580dcb0b40a8ebe1bd45976235f2f518d0adc0b/src/libjasper/jpc/jpc_t2dec.c#L369 and corresponding https://github.com/jasper-software/jasper/blob/9580dcb0b40a8ebe1bd45976235f2f518d0adc0b/src/libjasper/jpc/jpc_ …

Fix wrong checking EPH marker

---

src/libjasper/base/jas_debug.c
src/libjasper/base/jas_icc.c
src/libjasper/base/jas_stream.c
src/libjasper/bmp/bmp_dec.c
src/libjasper/include/jasper/jas_debug.h
src/libjasper/include/jasper/jas_stream.h
src/libjasper/jp2/jp2_cod.c
src/libjasper/jp2/jp2_cod.h
src/libjasper/jp2/jp2_dec.c
src/libjasper/jp2/jp2_enc.c
src/libjasper/jpc/jpc_cs.c
src/libjasper/jpc/jpc_dec.c
src/libjasper/jpg/jpg_val.c
src/libjasper/mif/mif_cod.c
src/libjasper/pgx/pgx_dec.c
src/libjasper/pnm/pnm_dec.c
src/libjasper/ras/ras_dec.c

Reduces memory usage a bit and speeds up the decoder by 5-10%.

Bulk I/O optimizations for jas_stream

---

src/libjasper/jpc/jpc_t2dec.c

**Why**: If SOP marker segments are allowed (by setting the second LSB of Scod parameter to "1" in the COD marker segment, see A.6.1 in the spec), each packet in any given tile-part may or may not be appended with an SOP marker segment. So, the decoding process should not be stopped by missing SOP markers. However, whether or not the SOP marker segment is used, the count in the Nsop (packet sequence number) is incremented for each packet.
**How**: Added code lines to check packet sequence number when a SOP is found and to show warning message when a SOP is missing.
FYI: `Nsop` is a field which has 16 bits length. Valid range of the value of `Nsop` is from 0 to 65535. The first packet in a coded tile is assigned the value zero. For every successive packet in this coded tile, this number is …

Fix SOP marker checking

---

src/libjasper/jpc/jpc_t2dec.c

fix #233
**Why**: The commit 13390bd said "the `dec->numpkts` holds the number of packets that have been already read. Because the maximum value of `Nsop` is 65535, `dec->numpkts % 65536` is necessary to validate a `Nsop` value in a SOP marker segment.", however, this was wrong.
**How**: Instead of the `dec->numpkts`, `tile->pi->pktno` is used to validate a `Nsop` because the `Nsop` is defined as packet seqence number in a **tile**. `tile->pi->pktno` holds the packet seqence number in a certain tile.

Hotfix to SOP marker checking

---

src/libjasper/include/jasper/jas_cm.h
src/libjasper/include/jasper/jas_debug.h
src/libjasper/include/jasper/jas_icc.h
src/libjasper/include/jasper/jas_image.h

closes https://github.com/mdadams/jasper/issues/217

Fix exported symbols

---

src/libjasper/base/jas_image.c
src/libjasper/jp2/jp2_dec.c

The fix was not backported from jasper-maint properly.
The commit 27d5a884598e909b6e88ee8bf0c5db300a418adb (see jasper-maint/jasper#25)
`numlutens` field is only validate in the encoder,
but `jas_image_depalettize` is used only in the decoder. The decoder should validate incoming data,
otherwise specifically crafter file can crash the application.
If `numlutents` is exactly 0 `v` can too big as unsigned `-1` on line 1044

Fix for CVE-2018-19541

---

src/libjasper/jpc/jpc_dec.c

We fixed input validation as part of the fix for [ZDI-15-529](https://www.zerodayinitiative.com/advisories/ZDI-15-529/)

Fix for ZDI-15-529

---

build/jasper.pc.in

For example, GEGL (gegl.org) uses that style of include.

Add -I<include_dir> to support users that use #include <jasper/jasper.h>

---

NEWS

Capitalize first letter.
Use present tense.
Like it is done in the first entry.
Let's stay consistent.
Let's link the corresponding issues for reference.
In the case where the issue is actually directly reported in a PR with a
fix, use that instead.
Clarify about CVE-2018-19541 decoder/encoder, otherwise users might be
confused why we claim to have it fixed in 2.0.20 already.

Improve NEWS file

---

CMakeLists.txt

Moved the point at which the JasPer OpenGL CMake module is included in the top-level CMakeLists.txt file so that the main JasPer config header is generated correctly and all of the initialization required for this module is performed prior to its inclusion.

Fix for GLUT-related build issue

---

src/libjasper/jpc/jpc_enc.c

Check maxrlvls to avoid more than the upper bound.

Avoid maxrlvls more than upper bound to cause heap-buffer-overflow

---

src/libjasper/base/jas_image.c

Fixes stack overflow bug on Windows, where variable-length arrays are
not available.  Unlike VLAs, _alloca() calls accumulate, and calling
it in every loop iteration is certainly a bad idea.
Regression from commit 5017d3ab2eae49957c3e41cbf9df207b1f31f3bd
Closes https://github.com/jasper-software/jasper/issues/256

jas_image: call _alloca() only once

---

src/libjasper/jpc/jpc_enc.c

If this ternary operation creates a problem on some clang version.
Why not just use the more readable if clause in all cases?
https://github.com/jasper-software/jasper/issues/260 further reports
that it also creates problems on intel compilers.
Instead of adding more and more checks for compatible compilers let's
just use the if clause.
Fixes https://github.com/jasper-software/jasper/issues/260

Remove ternary operation only done on some compilers

---

src/libjasper/pgx/pgx_dec.c

if prec is 31, this leads to an undefined shift

fix another potential source of undefined behavior

---

src/libjasper/include/jasper/jas_math.h

Not all versions of clang have these builtins, so use clang's
`__has_builtin` macro to check that they are available before using.

Fix check for overflow builtins

---

src/libjasper/include/jasper/jas_compiler.h

GCC 4.2 fails to compile Jasper 2.0.32 as described here: https://trac.macports.org/ticket/63300
`__builtin_unreachable()` was added in GCC 4.5. Add some macro logic to address this.

Use `__builtin_unreachable()` only with GCC 4.5+

---

src/libjasper/include/jasper/jas_math.h

y.valid was used where we wanted y.value.
It got introduced with commit def49688. So JasPer versions affected are: 3.0.0 until 3.0.3.
Fix https://github.com/jasper-software/jasper/issues/323

Fix value in jas_safeui64_div

---

src/libjasper/base/jas_cm.c
src/libjasper/jp2/jp2_dec.c

Incorrect ICC color profile should not kill the application.
Just report an issue and continue. It is not a critical issue.

Don't crash the application if ICC color profile is incorrect

---

build/cmake/modules/JasGetStdcVersion.cmake

When I build jasper project embedded into another CMake project it fails to find `build/cmake/src/print_stdc.c` because `CMAKE_SOURCE_DIR` does not point to the root of jasper. Use relative path for search

Allow building inside another project

---

src/app/jasper.c

fix #332: memory leaks in function cmdopts_parse

fix memory leaks in function cmdopts_parse

---

build/jasper.pc.in

This defines LIBJASPER_STATIC_DEFINE when static linking is expected.
The Cflags.private field depends on pkgconf rather than pkg-config.
Without this change, linker finds exported APIs with dllimport and
it produces the error:
```
ld.exe: test_1.c:(.text+0x2b): undefined reference to `__imp_jas_get_total_mem_size'
ld.exe: test_1.c:(.text+0x4b): undefined reference to `__imp_jas_optarg'
```
and more.
Result of this change:
* Before:
$ pkgconf -cflags -static jasper
-IF:/msys64/ucrt64/include/jasper -IF:/msys64/ucrt64/include
* After:
$ pkgconf -cflags -static jasper
-IF:/msys64/ucrt64/include/jasper -IF:/msys64/ucrt64/include -DLIBJASPER_STATIC_DEFINE

pkgconfig: Add Cflags.private field for static linking

---

CMakeLists.txt
build/jasper.pc.in

Requires.private field is required to link dependent libraries while static linking. For example, here libjpeg and libheif. `pkgconf -libs -static` command will show the dependent libraries. This helps to manage the dependent libraries automatically in build system without adding them explicitly while static linking. More information about this feature can be found here https://people.freedesktop.org/~dbn/pkg-config-guide.html

pkgconfig: Add Requires.private field for static linking

---

CMakeLists.txt

The external build system can specify debug suffix if it is needed.
Close #350.

Don't force debug suffix

---

doc/CMakeLists.txt

according to cmake docs DEPENDS in add_custom_command with file being output of other custom command:
> If any dependency is an OUTPUT of another custom command in the same
> directory (CMakeLists.txt file), CMake automatically brings the other
> custom command into the target in which this command is built.
this means "manual_pdf" target will not wait for previous doxygen invocation but will trigger its own. in case of parallel build two doxygen invocations with same input parameters might overwrite each other's output resulting in broken files. it could be verified with just grepping cmake output:
```console
$ grep -r 'doxygen Doxyfile' builddir/doc
builddir/doc/CMakeFiles/doc.dir/build.make:	cd /home/users/builder/rpm/BUILD/jasper-3.0.6/builddir/doc && /usr/bin/doxygen Doxyfile …
```

doc/CMakeLists.txt: fix prallel build of api docs and pdf manual

---

test/bin/run_test_3

`which` is non-portable (not part of POSIX) and distributions like Debian and Gentoo are looking to remove it from their base set of packages.
Switch to `type -P` instead given `test/bin/run_test_3` already has a Bash shebang.

test: run_test_3: drop use of `which`

---

CMakeLists.txt

This PR replaces `${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}` with `${CMAKE_INSTALL_FULL_LIBDIR}`, as the latter is more standard, and the former could actually result in wrong paths ([see this](https://bugzilla.redhat.com/show_bug.cgi?id=795542)).
The issue is observed in Nixpkgs, where an output separation doesn't pass cyclic output detection on macOS: NixOS/nixpkgs#293480

CMakeLists.txt: fix absolute path

---

NEWS.txt

Add reference to CVE-2025-8836, CVE-2025-8837 in NEWS document
